version: '3.9'

services:
  api:
    build: .
    container_name: savory-api
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
    volumes:
      - ./app:/app

  mongo:
    image: mongo:latest
    container_name: savory-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: